Feature
bluejoyq/react-studies pull request #1
Opened 2023-07-23 16:31 UTC by kimseo-0

2023-07-25 09:17 UTC, bluejoyq requested changes
한번 수정해주세요

2023-07-25 09:17 UTC, gene-ss commented on 0_1/src/App.tsx
> +  const isOverflow = (num: string) => {
isOverflow는 단순 판단의 역활만 할 것이라고 기대했는데, 상태까지 바꾸고 있어 이름이 부적절한 것 같습니다.

2023-07-25 09:17 UTC, gene-ss commented on 0_1/src/App.tsx
> +export enum type {
불필요한 export인 것 같아요. 그것과 별개로 type같은 범용적인 이름을 naming export하는 건 혼동의 우려가 있어 좋지 않은 것 같습니다.

2023-07-25 09:17 UTC, gene-ss commented on 0_1/src/App.tsx
> +          gridTemplateColumns: `repeat(${4}, 1fr)`,
@kimseo-0 여기에 백틱 문자열을 쓰신 이유가 뭔가요?

2023-07-25 09:17 UTC, gene-ss commented on 0_1/src/App.tsx
> +let curType: number = type.Number;
이렇게 변수를 사용하면, 컴포넌트 라이프 사이클과 별도로 상태가 유지될 것 같습니다.
useRef를 사용해서 개선해보는건 어떨까요?
https://ko.react.dev/reference/react/useRef 의 ref로 값을 참조하기 섹션을 참고하시면 좋을 것 같아요.

2023-07-25 09:17 UTC, bluejoyq commented on 0_1/src/App.tsx
> +        <button onClick={() => addNumber('7')}>7</button>
반복되는 addNumber를 반복문으로 처리하면 코드 양과 가독성을 개선할 수 있을 것 같아요.

2023-07-25 09:17 UTC, gene-ss commented on 0_1/src/App.tsx
> +let operations: Array<string> = [];
operations라는 변수 명은 기호만 담을 것 같아요. 다른 적절한 이름이 있을 것 같습니다!

2023-07-25 09:17 UTC, bluejoyq commented on 0_1/src/App.tsx
전체적인 리뷰
- `operations`라는 전역 변수를 사용해서 코드가 엉킨 것 같아요. 만약 기호를 무한정 누르면 메모리에 계속 쌓이는 등의 문제가 있을 것 같습니다.
- `display` 변수의 타입이 굳이 string이여서 코드 양이 늘어난 느낌이에요. number로 유지하고, 에러 케이스는 별도의 변수 혹은 상태를 가지고 표현해주면 어떨까요?

2023-07-25 09:21 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +          gridTemplateColumns: `repeat(${4}, 1fr)`,
ㅋㅋㅋ어디서 복붙해와서 그럼

2023-07-25 09:51 UTC, kimseo-0 commented on 0_1/src/App.tsx
1번 항목에 대해서는
기호를 무한정 눌러 메모리가 쌓이지 않습니다.
기호를 한번 선택하면 다음에 누르는 기호는 처리를 하지 않습니다.

문제에서
더하기 기호를 선택한 후, 마이너스 기호를 선택했을 때
어떻게 처리할 것인지에 대한 부분에 대한 설명이 추가되어야할 것 같습니다.

2023-07-25 09:54 UTC, bluejoyq commented on 0_1/src/App.tsx
그렇네요. 다음에는 개선하겠습니다.

2023-07-25 09:55 UTC, kimseo-0 commented on 0_1/src/App.tsx
2번 항목은
의도한게 맞는데
display 를 숫자로 처리할 수 있는 방법이 생각나서 수정해볼게요

2023-07-25 13:46 UTC, kimseo-0 commented on 0_1/src/App.tsx
만약 display 가 number 면 소수점 . 처리는 어떻게 하실건가요??

2023-07-25 15:08 UTC, gene-ss commented on 0_1/src/App.tsx
소수점 처리를 별도로 해줄 필요가 있나요? JS의 Number는 실수 정수를 모두 포함하는 자료형이지 않나요?

2023-07-25 15:35 UTC, kimseo-0 commented on 0_1/src/App.tsx
예를들어서 
1. 까지 친 상태일때 
number 로 처리하면 그냥 1 이라고 인식하기 때문에
결국 이후 숫자가 소수점 이하 자리라는걸 처리해야합니다.

2023-07-25 15:37 UTC, kimseo-0 commented on 0_1/src/App.tsx
추가로
Error 라 Overflow 가 떴을 때,

바로 숫자를 누르면 계산기 사용이 가능한지에 대한 조건이 추가되어야 할 것 같습니다.

현재 코드는 가능하게 되어있는데, AC 를 눌러야 사용가능한지 이런 부분에 대한 언급이 잇으면 좋을거 같습니다.

2023-07-27 10:35 UTC, bluejoyq requested changes

2023-07-27 10:35 UTC, gene-ss commented on 0_1/src/App.tsx
> +// let curType: number = inputDataType.Number;
굳이 주석으로 남기지 말고 삭제하는게 어떤가요

2023-07-27 10:35 UTC, gene-ss commented on 0_1/src/App.tsx
> +  const curType: React.MutableRefObject<inputDataType> = useRef(
제가 생각한 느낌이 바로 이런거에요 ㅋㅋ

2023-07-27 10:35 UTC, gene-ss commented on 0_1/src/App.tsx
> +  const curType: React.MutableRefObject<inputDataType> = useRef(
굳이 curType이 필요 없지 않을까요? 어차피 마지막에 입력한 기호의 종류는 operations에 있으니까

2023-07-27 10:35 UTC, gene-ss commented on 0_1/src/App.tsx
> +    for (let i = 2; i < operations.current.length; i = i + 2) {
반복문이 왜 필요한가 했더니, 이전의 연산 기호와 숫자들을 계속 유지하고 있네요. 굳이 이럴 필요 없이, 한번 계산할때 pop으로 꺼내서 결과만 append 하면 더 좋지 않을까요?

2023-07-27 10:35 UTC, gene-ss commented on 0_1/src/App.tsx
음 그렇네요. 1.0으로 만들어서 소수로 인식시키는 방법은 어떤가요

2023-07-27 10:35 UTC, gene-ss commented on 0_1/src/App.tsx
> +}
이 위의 이넘들은 파일을 분리해도 괜찮았을 것 같아요.

2023-07-27 10:35 UTC, gene-ss commented on 0_1/src/App.tsx
> +        key: 'AC',
key보다 보여지는 이라는 의미가 담긴 속성 명이였으면 더 좋을 것 같아요 ex) label

2023-07-27 10:35 UTC, gene-ss commented on 0_1/src/App.tsx
> +          fontSize: '15vmin',
@kimseo-0 폰트 사이즈에 vmin을 쓴 이유가 뭔가요...?

2023-07-27 10:35 UTC, gene-ss commented on 0_1/src/App.tsx
> +  const renderKey = (type: keyType, key: string, value: number) => {
위에서 keyDataType 멋있게 정의해서 click 만들어 놓고 여기서 별도로 이렇게 케이스를 다 나눠가면서 만드는 이유가 뭔가요!! 저는 이 함수는 불필요하다고 생각해요

2023-07-27 10:35 UTC, gene-ss commented on 0_1/src/App.tsx
> +  const handleKeyUp = (e: any) => {
최초에 렌더링 시에만 사용한다면 useCallback으로 감싸서 불필요한 렌더링을 막아주는게 어떤가요

2023-07-27 10:35 UTC, gene-ss commented on 0_1/src/App.tsx
> +  ZERO,
keytType ZERO로 인해 달라지는게 스타일 말고는 아무것도 없는데 스타일을 keyDataType에 추가하거나 키 타입에 따라 스타일을 반환하는 함수 추가하는 등의 방법으로 통합시킬 수 있을 것 같아요.

2023-07-27 10:39 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +    for (let i = 2; i < operations.current.length; i = i + 2) {
처음에 기존 계산기처럼  1 +  2 - 3 
이런 식으로 디스플레이에 다 보여줄 생각을 가지고 만들어서 그 구조를 유지했는데, 이 문제로 따지면 사실 그럴 필요 없긴 하죠...ㅎ

2023-07-27 10:40 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +  const renderKey = (type: keyType, key: string, value: number) => {
그럼 어떻게 하는게 좋은거죠?

2023-07-27 10:42 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +  const curType: React.MutableRefObject<inputDataType> = useRef(
저 curType 은 기수와 소수를 구분하기 위해 있는겁니다

2023-07-27 10:52 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +  const renderKey = (type: keyType, key: string, value: number) => {
아 그러네 저거 만들고 적용을 안했네요..하하

2023-07-27 11:49 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +          fontSize: '15vmin',
화면 비율로 글자 사이즈 조절을 하고 싶었어요.
display 사이즈가 폰트사이즈에 자동으로 맞춰지게, height 설정을 안해뒀거든요

2023-08-02 13:45 UTC, bluejoyq requested changes

2023-08-02 13:45 UTC, gene-ss commented on 0_1/src/App.tsx
> +        key: 0,
불필요한 변수입니다.

2023-08-02 13:45 UTC, gene-ss commented on 0_1/src/App.tsx
> +        {keyData[0].map((data: keyDataType) => {
keyData를 굳이 2개의 리스트로 나눌 필요가 있나요? grid의 속성을 잘 이용하면 그렇지 않아도 될 것 같습니다.

2023-08-02 13:45 UTC, gene-ss commented on 0_1/src/App.tsx
> +  const handleKeyUp = (e: any) => {
이거 왜 type이 any에요

2023-08-02 14:10 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +        key: 0,
불필요하지 않습니다.
버튼들을 foreach 로 만들때
key 를 설정해주어야합니다

2023-08-02 14:10 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +        key: 0,
저는 그냥 임의로 숫자로 설정했습니다....

2023-08-02 14:11 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +        {keyData[0].map((data: keyDataType) => {
잘보시면 className 이 각각 다른것을 확인할 수 있습니다.
결국 그리드를 두개로 나눠야 합니다.

혹시 다른 방법이 있으면 알려주세요

2023-08-02 14:12 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +  const handleKeyUp = (e: any) => {
KeyboardEvent 이네요
타입이 먼지 몰라서 일단 any 로 했습니다

2023-08-02 14:28 UTC, bluejoyq commented on 0_1/src/App.tsx
> +        key: 0,
애초에 label이 고유값이라서 불필요하다고 생각합니다.

2023-08-02 14:32 UTC, bluejoyq commented on 0_1/src/App.tsx
> +        {keyData[0].map((data: keyDataType) => {
2칸을 차지해야하는 아이템에게 이 속성을 부여하는건 어떤가요.
`grid-column: auto / span 2;`

2023-08-02 14:32 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +        key: 0,
물론 당장 이 코드에서 필요는 없죠.

매우 장기적이고 협업의 관점에서
팀 내에서 각 버튼 별로 가지고 있는 code값이 있을 것이라고 가정 했고,

그냥 label 로 작성하는 것보다는 해당 code 로 key 를 정하는 것이 좋을 것이라고 판단했습니다.

key 값을 개인적으로 code 를 만들까 하다가 그건 너무 과한거 같아서 그냥 적당히 숫자로 넣은거고요

2023-08-02 14:33 UTC, gene-ss commented on 0_1/src/App.tsx
> +        key: 0,
key의 목적은 리액트에서 해당 컴포넌트가 동일한지 확인하는 용도인데, 별도의 key 없이도 label로도 구분이 됩니다!! 그리고 key에 순서를 적을거면 차라리 forEach나 map의 두번째 props를 이용하는게 나을 것 같습니다.

2023-08-02 14:34 UTC, kimseo-0 commented on 0_1/src/App.tsx
> +        key: 0,
label 값이 이후에도 변경될 것이라는 점이랑 임의로 숫자로 넣었다는 점을 고려해도 불필요하다고 생각하면 지우죠

2023-08-02 14:38 UTC, bluejoyq commented on 0_1/src/App.tsx
> +        key: 0,
이거 애매하긴한데, label끼리 중복될 일은 없어서 상관 없을 것 같아요.

2023-08-06 08:46 UTC, bluejoyq approved these changes

2023-08-06 08:46 UTC, merged